
COMPONENT_ADD_INCLUDEDIRS := \
	include \
	ports/esp32	\

COMPONENT_SRCDIRS := \
	src\
	ports/esp32\
#CFLAGS += -O0 -g
CFLAGS +=  -DDEBUG_ENABLED=1 -Wall -Wmissing-prototypes -DPRINT_ENABLED=1 -DBACAPP_ALL -DBACNET_PROPERTY_LISTS=1 -DBACDL_BIP=1 -DBBMD_ENABLED=1 -DWEAK_FUNC=
 
